//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Swappler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwapRequest
    {
        public System.DateTime Date { get; set; }
        public Nullable<long> MoneyOffer { get; set; }
        public bool Active { get; set; }
        public long SwapItemId { get; set; }
        public Nullable<long> SwapItemOfferId { get; set; }
        public System.Guid Guid { get; set; }
        public long UserId { get; set; }
        public long SwapRequestId { get; set; }
    
        public virtual SwapItem SwapItem { get; set; }
        public virtual SwapItem SwapItem1 { get; set; }
        public virtual User User { get; set; }
    }
}
